language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: DTNZz2O0fW0TAZ2nipV7+Sr5Hyp7GrOy6WdkaypgnS96lYr4XL4Z8rTgrQSBVxpuY8HNSDK0DJosC9baGps7Lrzbzxzv+CKa5Suwbt3l4awYeVMS9+65PCw0XnBT6d7ZaDgpPDbNGUvS2AMhdefVA+77lAzICk858X+0puDuBJXVWhphvu6Pn3UvBLjqUxlVjtHb8gv3oIhqirp2wEA2/VgMgQnaDNAkUFsacwbkXjsqCD7IwYNIZyR4b7vYaP12/sTzKAc1TGHmSll906yU5Nw2Q7ZNeWC/h/Uwbof6RnK9YGVwRwyBFQn4lgvn1xka2uIAzjVApSqa9gVuApoJlUS6516B/N33mtkla3khZhvXiGYPATVETUxePUJIMBey+LrL+028em/8Any6s3EMVI4IplwekTOytNEPDjyQctJXiD3/H/+eKn9wos0Do9w4M6x4Tg8g4k5MCA8IoGj2Y3XXC7EpYzISCLEOgeA+2YEl9Fw+tytL/U6Ce4hC6ZdDvuRGZnjdCs+m9/eHkmmtkS2cxU2eakZhuC0DfMlDxewmoSxzN5BiHvR7QZPnzEF8pfU/yVRmzTEl9F5Jh3nbfZhy3+WMjAjyn2acW1vufuIk1d+RaBwi0osEBBQmbWgDECI9hXe1LYzPd0yXRd9VPejv9nlB7kITk8KW7Ta55sM=
  app: salty-escarpment-43706
  on:
    repo: jbvance/thinkful-react-capstone-client
